In [1]:
import numpy as np

In [3]:
a = np.arange(10)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([1,2,3,4,5,6,7,8,9],dtype = int)

In [7]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(b)

numpy.ndarray

In [9]:
type(a)

numpy.ndarray

In [10]:
c = np.arange(12).reshape(2,6)

In [12]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
c.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [15]:
c = c.reshape(6,2)

In [16]:
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [17]:
x = np.eye(2,2,dtype = float)

In [18]:
x

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
x = np.eye(2,3,dtype = int)

In [20]:
x

array([[1, 0, 0],
       [0, 1, 0]])

In [21]:
x = np.identity(2)

In [22]:
x

array([[ 1.,  0.],
       [ 0.,  1.]])

In [23]:
v = np.identity(3)

In [24]:
v

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
v = np.identity(3,dtype = int)

In [26]:
v

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
m = np.empty([2,2],dtype = int)

In [39]:
m

array([[0, 0],
       [0, 0]])

In [40]:
l = np.zeros([2,3])

In [41]:
l

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [44]:
n = np.ones([3,3],dtype = int)

In [45]:
n

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
p = np.empty_like(n)

In [47]:
p

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
p = np.zeros_like(n)

In [49]:
p

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
p = np.ones_like(n)

In [51]:
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [52]:
len(p)

3

In [54]:
p.shape

(3, 3)

In [55]:
m = np.linspace(2,3,5)

In [56]:
m

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [57]:
m.astype(int)

array([2, 2, 2, 2, 3])

In [58]:
m

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [59]:
m = m.astype(int)

In [60]:
m

array([2, 2, 2, 2, 3])

In [62]:
z = np.array([[1,2,3],[4,5,6]])

In [63]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
z.shape()|

SyntaxError: invalid syntax (<ipython-input-64-4a0aafb701c0>, line 1)

In [65]:
z.shape

(2, 3)

In [71]:
type(z.shape[0])

int

In [73]:
for i in range(0,z.shape[0],1):
    print(i)

0
1


In [66]:
z[0][0]

1

In [74]:
for i in range(0,z.shape[0],1):
    for j in range(0,z.shape[1],1):
        print("Element at index i ",i," j ",j," is ",z[i][j])

Element at index i  0  j  0  is  1
Element at index i  0  j  1  is  2
Element at index i  0  j  2  is  3
Element at index i  1  j  0  is  4
Element at index i  1  j  1  is  5
Element at index i  1  j  2  is  6


In [75]:
v = np.array([1,2,3])

In [76]:
u = np.array([4,5,6])

In [78]:
v*u

array([ 4, 10, 18])

In [80]:
a = np.array([[2,2],[2,2]])

In [81]:
a

array([[2, 2],
       [2, 2]])

In [82]:
a.dot(a)

array([[8, 8],
       [8, 8]])

In [84]:
a.dot(np.identity(2,dtype = int))

array([[2, 2],
       [2, 2]])

In [85]:
b = np.array([[1,2],[3,4]])

In [86]:
b.mean()

2.5

In [87]:
b.mean(0)

array([ 2.,  3.])

In [88]:
b.mean(1)

array([ 1.5,  3.5])

In [89]:
h = np.random.random((2,3))

In [90]:
h

array([[ 0.69517438,  0.88861011,  0.6991161 ],
       [ 0.0037069 ,  0.58207678,  0.67502846]])

In [91]:
np.max(h)

0.8886101147311346

In [92]:
np.min(h)

0.0037069039600828857

In [94]:
np.sum(h)

3.5437127499477752

In [96]:
h.max()

0.8886101147311346

In [97]:
h.min()

0.0037069039600828857

In [99]:
h.min(axis = 0)

array([ 0.0037069 ,  0.58207678,  0.67502846])

In [100]:
h

array([[ 0.69517438,  0.88861011,  0.6991161 ],
       [ 0.0037069 ,  0.58207678,  0.67502846]])

In [101]:
h.max(axis = 1)

array([ 0.88861011,  0.67502846])

In [102]:
h = np.array([[1,2,3],[4,5,6]])

In [103]:
h.sum(axis = 0)

array([5, 7, 9])

In [104]:
h.sum(axis = 1)

array([ 6, 15])

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a = np.array([[1,2,3],[4,5,6]])

In [5]:
a.min()

1

In [6]:
a.max()

6

In [7]:
a.sum()

21

In [8]:
a.sum(axis = 0)

array([5, 7, 9])

In [9]:
a.min(axis = 1)

array([1, 4])

In [11]:
a.sum(axis = 1)

array([ 6, 15])

In [14]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [18]:
for i in a:
    print(i[1:])

[2 3]
[5 6]


In [19]:
for i in a.flat:
    print(i)

1
2
3
4
5
6


In [ ]:
x = [1,2,3,4,5]
y = []